# Generated by Django 5.0.6 on 2024-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentmode_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
