# Generated by Django 5.0.6 on 2024-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dailyexpense_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_deposited',
            field=models.BooleanField(default=False),
        ),
    ]
