# Generated by Django 5.0.6 on 2024-08-17 22:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymenttransaction_is_deposited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(2000)])),
                ('cb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ob', to='core.paymentmode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('month', 'year', 'payment_mode', 'user')},
            },
        ),
    ]
