# Generated by Django 5.0.6 on 2024-07-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymenttransaction_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexpense',
            name='comment',
        ),
    ]
